---
title: "例外処理ステートメント (C# リファレンス)"
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
dev_langs:
- CSharp
helpviewer_keywords:
- keywords [C#], exception handling
ms.assetid: 6d0323a3-3164-411c-9b84-a3606bd0e13c
caps.latest.revision: 12
author: BillWagner
ms.author: wiwagn
translation.priority.ht:
- cs-cz
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- pl-pl
- pt-br
- ru-ru
- tr-tr
- zh-cn
- zh-tw
ms.translationtype: HT
ms.sourcegitcommit: 306c608dc7f97594ef6f72ae0f5aaba596c936e1
ms.openlocfilehash: 0c60adc167fc585755c8bbb85a05cf2af025edd3
ms.contentlocale: ja-jp
ms.lasthandoff: 07/28/2017

---
# <a name="exception-handling-statements-c-reference"></a>例外処理ステートメント (C# リファレンス)
C# では、プログラムの実行時に発生する例外と呼ばれる異常事態を処理する組み込みサポートが用意されています。 このような例外は、通常の制御フローの外部にあるコードによって処理されます。  
  
 ここでは、例外処理に関する次のトピックについて説明します。  
  
-   [throw](../../../csharp/language-reference/keywords/throw.md)  
  
-   [try-catch](../../../csharp/language-reference/keywords/try-catch.md)  
  
-   [try-finally](../../../csharp/language-reference/keywords/try-finally.md)  
  
-   [try-catch-finally](../../../csharp/language-reference/keywords/try-catch-finally.md)  
  
## <a name="see-also"></a>関連項目  
 [C# リファレンス](../../../csharp/language-reference/index.md)   
 [C# プログラミング ガイド](../../../csharp/programming-guide/index.md)   
 [C# のキーワード](../../../csharp/language-reference/keywords/index.md)   
 [ステートメントのキーワード](../../../csharp/language-reference/keywords/statement-keywords.md)   
 [例外と例外処理](../../../csharp/programming-guide/exceptions/index.md)

